# Generated by Django 5.1.1 on 2024-11-11 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0003_remove_content_horizontol_poster_content_slider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "source_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("source_title", models.CharField(max_length=255)),
                ("source_quality", models.CharField(max_length=100)),
                ("source_size", models.CharField(max_length=100)),
                ("downloadable", models.BooleanField(default=False)),
                ("access_type", models.CharField(max_length=100)),
                ("source_type", models.CharField(max_length=100)),
                ("source", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_id",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.content",
                    ),
                ),
            ],
        ),
    ]
