# Generated by Django 5.1.1 on 2024-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_season", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="trailer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
