# Generated by Django 5.1.1 on 2024-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_season", "0002_alter_season_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="image",
            field=models.TextField(blank=True),
        ),
    ]
