# Generated by Django 5.1.1 on 2024-11-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_season", "0003_alter_season_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="season",
            name="image",
            field=models.ImageField(upload_to="Season-image"),
        ),
        migrations.AlterField(
            model_name="season",
            name="trailer",
            field=models.FileField(blank=True, null=True, upload_to="Season-trailer"),
        ),
    ]
