# Generated by Django 5.1.1 on 2024-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_alter_network_network_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
