# Generated by Django 5.1.1 on 2024-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0004_alter_network_network_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="network_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
