# Generated by Django 5.1.1 on 2024-11-11 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episode_content_source", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodes",
            name="season_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="episodes",
            name="episode_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
