# Generated by Django 5.1.1 on 2024-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="Horizontol_poster",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="verticle_poster",
            field=models.TextField(blank=True),
        ),
    ]
