# Generated by Django 5.1.1 on 2024-11-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_horizontol_poster_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="Horizontol_poster",
        ),
        migrations.AddField(
            model_name="content",
            name="slider",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="content",
            name="verticle_poster",
            field=models.ImageField(blank=True, upload_to="verticle-poster"),
        ),
        migrations.AddField(
            model_name="content",
            name="horizontol_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="horizontol-poster"
            ),
        ),
    ]
